### PR TITLE
Fixed Hamburger visibility for dark mode

### PR DESCRIPTION
**Pull request by rutupatel53**
# Title and Issue number 

Title :Fixed Hamburger visibility for dark mode

Issue No. :#399

Code Stack : React,Antd

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

### CODE REVIEW

**Review by sadanandpai — APPROVED** [review]

**Comment by sadanandpai** [comment]
conflicts @rutupatel53

**Comment by rutupatel53** [comment]
> conflicts @rutupatel53

hey,Please check once again now there is no conflicts there.

**Comment by sadanandpai** [comment]
image

**Comment by rutupatel53** [comment]
i have resolved conflicts, i don't know why on your github it saws conflicts if any mistake from my side please suggest me.

Screenshot 2024-03-06 193425

**Pull request closed without merging**
