### PR TITLE
Updated Local Setup section

### LINKED ISSUE #198: Enhancement in Local stepup section
Currently the local setup look like this

I want to update this section so it would look like as shown below.

### PR DESCRIPTION
**Pull request by SusheelThapa**
Also formatted the readme and add more github badge

# Title and Issue number 

Title : Updated Local Setup section of README and added few more github badge.

Issue No. : #198 

Code Stack : markdown

Close #198 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [ ] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by SusheelThapa** [comment]
@sadanandpai Please review my pull request

**Comment by SusheelThapa** [comment]
@sadanandpai I have also solved #192

**Comment by arpansaha13** [comment]
Most of the text looks AI generated.

**Comment by SusheelThapa** [comment]
@arpansaha13 I admit that I have used AI generated text in some places. Shall I changes those text?

**Comment by arpansaha13** [comment]
The current README looks fine to me.
It is short and precise.
I don't think this change is necessary.

**Pull request closed without merging**
