### PR TITLE
Update challenges.ts

### PR DESCRIPTION
**Pull request by OhmRamwala**
# Title and Issue number 

Title :

Issue No. :

Code Stack : 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by arpansaha13** [comment]
You have created 3 Pull requests for one challenge and the files are split amkng 3 PRs

This is invalid. Everything should be in one PR.

**Comment by ZephyrXebec** [comment]
> You have created 3 Pull requests for one challenge and the files are split amkng 3 PRs
> 
> This is invalid. Everything should be in one PR.

How can i add three files in 1 pr? i am new sry

**Comment by arpansaha13** [comment]
Create ine PR and then keep commiting in the sane branch. All new changes will appear automatically

If you want i can Reopen this PR. And then you can keep pushing/comitting in this "patch-1" branch and they will appear here

**Comment by ZephyrXebec** [comment]
Yes Please and how can i commit to same pr can you share any doc or video?

**Comment by arpansaha13** [comment]
Checkout to the branch from where you created the PR. And then simply commit and push.

I am opening this PR. This PR is created from your "patch-1" branch. Try pushing in this "patch-1" branch.

**Pull request closed without merging**
