### PR TITLE
Create debugforangularinvscode.txt

### PR DESCRIPTION
**Pull request by nikcode9**
please merge it soon @sadanandpai

### CODE REVIEW

**Comment by sadanandpai** [comment]
@pankajparkar plz review this and merge if relevant

**Comment by pankajparkar** [comment]
@nikcode9 Developer console can help to debug the frontend project with ease. I'm so sorry, I'm not sure how this can be a good addition to project?

I think your PR could have been great addition for server side debugging purpose. WDYT @sadanandpai ?

**Comment by nikcode9** [comment]
@pankajparkar  i have just added a new file for how to debug in angular which was not there earlier and i dont think it should create any problem.

**Comment by sadanandpai** [comment]
As it has no impact, merging it. If it does not add any value, can be removed in future

**Pull request merged**
