### PR TITLE
Move the heading to the center .

### PR DESCRIPTION
**Pull request by pojith**

### CODE REVIEW

**Review by sadanandpai — CHANGES_REQUESTED** [review]
UI issue

**Comment by sadanandpai** [comment]
it shows broken 
https://deploy-preview-409--frontend-mini-challenges.netlify.app/

**Comment by sadanandpai** [comment]
image
this what I see

**Comment by pojith** [comment]
i will see

**Comment by sadanandpai** [comment]
the PR is outdated. Closing it. Please raise a new PR if any plans to work on this. @pojith

**Pull request closed without merging**
