### PR TITLE
Added My contribution

### PR DESCRIPTION
**Pull request by ankit071105**

### CODE REVIEW

**Comment by arpansaha13** [comment]
@ankit071105  Please explain the purpose of this pull request in your PR description

**Comment by arpansaha13** [comment]
It looks like you are trying to add a light-dark toggler. But the toggle is overlapping some of the existing UI.

image

Also, you have added the code in the root `index.html` and `vue/index.html` files. Those are not the correct places to put that code.

**Comment by ankit071105** [comment]
@arpansaha13 

Yes i was trying to add dark and light mode

**Comment by arpansaha13** [comment]
I see. I would like to guide you through some changes so that this feature can be made functional.

- The **home page** is made in React. So the toggle button should ideally be in the `react/src/components/navbar/Navbar.tsx` file.
- For the styles - you would need to write the **dark-mode alternative** for the styles in these files:
   - `react/src/components/hero/hero.module.scss`
   - `react/src/components/features/features.module.scss`
   - `react/src/components/testimonials/testimonials.module.scss`
   - `react/src/components/contribution/contribution.module.scss`
   - `react/src/components/footer/footer.module.scss`
- CSS changes _may_ be required in other places also. But these are the evident ones.

After this I believe the functionally will be working.

**Review by arpansaha13 — CHANGES_REQUESTED** [review]
I see. I would like to guide you through some changes so that this feature can be made functional.

- The **home page** is made in React. So the toggle button should ideally be in the `react/src/components/navbar/Navbar.tsx` file.
- For the styles - you would need to write the **dark-mode alternative** for the styles in these files:
   - `react/src/components/hero/hero.module.scss`
   - `react/src/components/features/features.module.scss`
   - `react/src/components/testimonials/testimonials.module.scss`
   - `react/src/components/contribution/contribution.module.scss`
   - `react/src/components/footer/footer.module.scss`
- CSS changes _may_ be required in other places also. But these are the evident ones.

After this, I believe the functionality will be working in the home page.

**Pull request closed without merging**
