### PR TITLE
Roll dice - Vanilla JavaScript

### PR DESCRIPTION
**Pull request by babandakale**
# Title and Issue number 

Title : Roll dice - Vanilla JavaScript

Issue No. :

Code Stack : HTML, CSS, JavaScript

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by sadanandpai** [comment]
Please follow the standards

https://github.com/sadanandpai/frontend-mini-challenges/blob/main/CONTRIBUTING.md

**Comment by babandakale** [comment]
@sadanandpai did changes as per your comment

**Comment by sadanandpai** [comment]
@babandakale Add yourself to the contributors list for your name to appear
image

Also can we keep UI to the center of the page
image
https://deploy-preview-365--frontend-mini-challenges.netlify.app/javascript/src/challenges/roll-dice/

**Comment by babandakale** [comment]
done

**Pull request merged**
