### PR TITLE
[React] Scroll-to-top button - closes #242

### LINKED ISSUE #242: Feature_Request: Add a back to top button.
**Is your feature request related to a problem? Please describe.**
The website has many challenges. Adding a scroll-to-top button will help in navigating through the website easily.

**Describe the solution you'd like**
I will like to add a scroll-to-top button component that will be work on all the pages of the website, near the bottom corner of the page.

**Demonstration of what I plan to do**
backtotop2

### PR DESCRIPTION
**Pull request by akash0708**
# Issue #242 : Scroll-to-top button.  

Title : Add back to top button

Issue No. : #242 

Code Stack :  React.js

Close #242 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

# Screenshot of implemented changes:

### Desktop:

back2

### Mobile:

back3

### CODE REVIEW

**Comment by akash0708** [comment]
@arpansaha13 please check and let me know if any changes are to be made. I have not checked the last two points in the checklist since it is a feature for the entire website not a part of any challenge.

**Review by arpansaha13 — CHANGES_REQUESTED** [review]
Looks good to me!

Please undo the changes in package.json and package-lock.json
Dependencies can be updated some other time

**Comment by akash0708** [comment]
Okay, doing it right away!

**Review by arpansaha13 — APPROVED** [review]

**Comment by akash0708** [comment]
@arpansaha13 , I have made the changes you asked for, is it okay now?

**Comment by arpansaha13** [comment]
yeah its good

**Pull request merged**
