### PR TITLE
Added a new Project [Hotstar clone]

### LINKED ISSUE #129: Hotstar Clone
**Describe the project you want to add with tech stack**

Hi Sir,
**I want to add a project on the Clone of the web platform HOTSTAR using HTML , CSS , JS. Please assign me the issue**
**Expected behavior**

It is a clone of HOTSTAR
**Screenshots (optional)**

**Additional context (optional )**

Please assign this to me.

### PR DESCRIPTION
**Pull request by apu52**
# Title and Issue number 

Title :
Hotstar Clone 
Issue No. :
#129
Code Stack : 
HTML , CSS ,JS
Close #129 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by apu52** [comment]
@sadanandpai Please take a review of my PR & merge it

**Comment by apu52** [comment]
@sadanandpai Please take a review of my PR & merge it

**Comment by apu52** [comment]
@sadanandpai Please take a review of my PR & merge it

**Comment by apu52** [comment]
@sadanandpai Please take a review of my PR & merge it

**Comment by arpansaha13** [comment]
This repo is for front-end logical challenges and not for full-blown websites/UIs.
Closing this PR as invalid.

**Pull request closed without merging**
