### PR TITLE
[WIP]feat/added dark-light theme and toggle button

### PR DESCRIPTION
**Pull request by Dev-AkshatGupta**
# Title and Issue number 
#393 Add dark and light mode for the host application
Title: feat/ dark - light theme and toggle button

Issue No. : #393 

Code Stack: Js, CSS

Close #<393>

# Description:- 
1. Using Lucid for icons instead of `Fontawesome` found it better.
2. Used Context for switching theme.
3. Example in a video.
https://github.com/sadanandpai/frontend-mini-challenges/assets/53713926/cf020e72-100f-404c-9d68-850d1c63468a

### CODE REVIEW

**Comment by sadanandpai** [comment]
conflicts

**Comment by sadanandpai** [comment]
@Dev-AkshatGupta 
image

**Comment by Dev-AkshatGupta** [comment]
> conflicts



> @Dev-AkshatGupta image

Hey Sadanand I added WIP for the same I know why it's happening and rectified it locally. Just having some trouble with the git configuration I am figuring that out. Will sqash all commits in one. Thanks for reviewing.

**Comment by Dev-AkshatGupta** [comment]
Opened a new pr with conflicts solved and commits squashed
https://github.com/sadanandpai/frontend-mini-challenges/pull/419

**Pull request closed without merging**
